### PR TITLE
ZEN-27995 Limit RabbitMQ to one instance

### PR DESCRIPTION
**Pull request by karolzen**
https://jira.zenoss.com/browse/ZEN-27995

### CODE REVIEW

**Comment by jplouis** [comment]
Build finished.

**Comment by jplouis** [comment]
Build finished.

**Comment by jplouis** [comment]
Build finished.

**Comment by karolzen** [comment]
retest this

**Comment by jplouis** [comment]
Build finished.

**Comment by jplouis** [comment]
Build finished.

**Comment by jplouis** [comment]
Build finished.

**Comment by jplouis** [comment]
Build finished.

**Pull request merged**
