### PR TITLE
ZEN-32003 Capacity ZenPack deployed with CZ doesn't run service migra…

### PR DESCRIPTION
**Pull request by romanbakaleyko**
…tions

### CODE REVIEW

**Review by jpeacock-zenoss — CHANGES_REQUESTED** [review]
Please revert the changes the files that have a change to their endings..

**Review by jpeacock-zenoss — CHANGES_REQUESTED** [review]
There should be service migration script to add the opentsdb-reader endpoint to these services.

**Comment by romanbakaleyko** [comment]
> Please revert the changes the files that have a change to their endings..

this comes from the 

> Please revert the changes the files that have a change to their endings..

This comes after I ran service-tool https://github.com/zenoss/zenoss-service/blob/develop/services/service-tool to fix definitions therefore I think it should go as is.

**Comment by romanbakaleyko** [comment]
> There should be service migration script to add the opentsdb-reader endpoint to these services.
I am not sure we do need it, the problem appears only for a fresh deployments since Capacity included in the bundle. For zenpack upgrade scenario endpoints set up during installation. https://github.com/zenoss/ZenPacks.zenoss.Capacity/blob/develop/ZenPacks/zenoss/Capacity/__init__.py#L28

**Review by jpeacock-zenoss — APPROVED** [review]

**Pull request merged**
